CREATE DATABASE [ASPMain]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ASPMain', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ASPMain.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ASPMain_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ASPMain_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [ASPMain] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [ASPMain] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ASPMain] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ASPMain] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ASPMain] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ASPMain] SET ARITHABORT OFF 
GO
ALTER DATABASE [ASPMain] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ASPMain] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ASPMain] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [ASPMain] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ASPMain] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ASPMain] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ASPMain] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ASPMain] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ASPMain] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ASPMain] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ASPMain] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ASPMain] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ASPMain] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ASPMain] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ASPMain] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ASPMain] SET  READ_WRITE 
GO
ALTER DATABASE [ASPMain] SET RECOVERY FULL 
GO
ALTER DATABASE [ASPMain] SET  MULTI_USER 
GO
ALTER DATABASE [ASPMain] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ASPMain] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ASPMain] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ASPMain]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [ASPMain]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [ASPMain] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

/* 创建数据表 gibberish */
/* 为了防止任何可能出现的数据丢失问题，您应该先仔细检查此脚本，然后再在数据库设计器的上下文之外运行此脚本。*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.gibberish
	(
	Id int NOT NULL IDENTITY (1, 1),
	TextJson nvarchar(MAX) NOT NULL,
	Name nvarchar(50) NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.gibberish SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
